# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines/*
      - src/*

pr: none

pool:
  vmImage: "windows-2019"

steps:
  - task: NodeTool@0
    displayName: "Use Node 16.x"
    inputs:
      versionSpec: 16.x

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm run build:production"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build:production"

  - task: CopyFiles@2
    displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)\\dist"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)\\dist"
      Contents: '**'
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: OneLuckiDev.json2variable.vsts-json-to-variable.oneLuckiDevJson2Variable@1
    displayName: "JSON to Variable"
    inputs:
      jsonFile: package.json
      shouldPrefixVariables: false

  - task: GitHubRelease@1
    displayName: "Publish Solution to GitHub"
    inputs:
      gitHubConnection: 'opc-buildbot'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(version)'
      assets: '$(Build.ArtifactStagingDirectory)/*'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
