# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines/*
      - src/*

pool:
  vmImage: "windows-2019"

steps:
  - task: NodeTool@0
    displayName: "Use Node 16.x"
    inputs:
      versionSpec: 16.x

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm run dist"
    inputs:
      command: custom
      verbose: false
      customCommand: "run dist"
